name: Generate Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows manually running the job at any time
  workflow_dispatch:
  
  # Run on every push on the master branch
  push:
    branches:
      - master
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generates a snake game from a GitHub user's (<github_user_name>) contributions graph,
      # outputs an SVG animation at <svg_out_path>
      - name: Generate GitHub Contribution Grid Snake SVG
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: MehraDevesh2022   # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      # Push the content of <build_dir> to a branch
      # The content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>,
      # or as a GitHub page
      - name: Push GitHub Contribution Grid Snake SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
